# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.cache/wt [current_project]
set_property parent.project_path /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/sources_1/imports/pt/Xilinx/Vivado/2018.1/bin/FirstCROPUF/Sources/ComparetwoRO.v
  /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/sources_1/imports/pt/Xilinx/Vivado/2018.1/bin/FirstCROPUF/Sources/Counter.v
  /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/sources_1/imports/ome/sreekanth/Downloads/PLL_BASE.v
  /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/sources_1/new/andga.v
  /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/sources_1/new/cro.v
  /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/sources_1/new/enhancedcro.v
  /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/sources_1/new/notga.v
  /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/sources_1/imports/new/rohmDRC.v
  /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/sources_1/imports/pt/Xilinx/Vivado/2018.1/bin/FirstCROPUF/Sources/ssdisplay.v
  /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/sources_1/imports/pt/Xilinx/Vivado/2018.1/bin/FirstCROPUF/Sources/ssdtop.v
  /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/sources_1/imports/new/uartmodDRC.v
  /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/sources_1/new/enhancedCROwrap.v
}
read_vhdl -library xil_defaultlib /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/sources_1/imports/new/UART_TXDDRC.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/constrs_1/new/TimingTop.xdc
set_property used_in_implementation false [get_files /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/constrs_1/new/TimingTop.xdc]

read_xdc /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/constrs_1/imports/Sources/Comparehmxdc.xdc
set_property used_in_implementation false [get_files /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.srcs/constrs_1/imports/Sources/Comparehmxdc.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top enhancedCROwrap -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef enhancedCROwrap.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file enhancedCROwrap_utilization_synth.rpt -pb enhancedCROwrap_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
