
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

#Uncomment for Seven Segment Display (ssd)
set_property PACKAGE_PIN J17 [get_ports {cen[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cen[0]}]
set_property PACKAGE_PIN J18 [get_ports {cen[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cen[1]}]
set_property PACKAGE_PIN T9 [get_ports {cen[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cen[2]}]
set_property PACKAGE_PIN J14 [get_ports {cen[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cen[3]}]
set_property PACKAGE_PIN P14 [get_ports {cen[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cen[4]}]
set_property PACKAGE_PIN T14 [get_ports {cen[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cen[5]}]
set_property PACKAGE_PIN K2 [get_ports {cen[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cen[6]}]
set_property PACKAGE_PIN U13 [get_ports {cen[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cen[7]}]

set_property PACKAGE_PIN T10 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property PACKAGE_PIN R10 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property PACKAGE_PIN K16 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN K13 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN P15 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN T11 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN L18 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN H15 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]

#For "done" output wire
set_property IOSTANDARD LVCMOS33 [get_ports done]
set_property PACKAGE_PIN U17 [get_ports done]

set_property PACKAGE_PIN D4 [get_ports txd]
set_property IOSTANDARD LVCMOS33 [get_ports txd]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN H17 [get_ports rst]

###### Four new input ports to selct the "CRO" among 16 CROs
set_property IOSTANDARD LVCMOS33 [get_ports {selcro[3]}]
set_property PACKAGE_PIN V10 [get_ports {selcro[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {selcro[2]}]
set_property PACKAGE_PIN U11 [get_ports {selcro[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {selcro[1]}]
set_property PACKAGE_PIN U12 [get_ports {selcro[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {selcro[0]}]
set_property PACKAGE_PIN H6 [get_ports {selcro[0]}]


####Tentatively for ro0 only, testing
##current_instance cropuf/comphm
#set_property BEL A6LUT [get_cells ro0/and1/c_INST_0]
#set_property LOC SLICE_X36Y92 [get_cells ro0/and1/c_INST_0]
#set_property LOCK_PINS {I0:A6 I1:A1} [get_cells ro0/and1/c_INST_0]
#set_property BEL B6LUT [get_cells ro0/not11/b_INST_0]
#set_property LOC SLICE_X37Y92 [get_cells ro0/not11/b_INST_0]
#set_property LOCK_PINS {I0:A6} [get_cells ro0/not11/b_INST_0]
#set_property BEL A6LUT [get_cells ro0/not21/b_INST_0]
#set_property LOC SLICE_X37Y92 [get_cells ro0/not21/b_INST_0]
#set_property LOCK_PINS {I0:A6} [get_cells ro0/not21/b_INST_0]
#set_property BEL F7AMUX [get_cells ro0/dedimux1]
#set_property LOC SLICE_X37Y92 [get_cells ro0/dedimux1]
#set_property BEL B6LUT [get_cells ro0/not12/b_INST_0]
#set_property LOC SLICE_X36Y93 [get_cells ro0/not12/b_INST_0]
#set_property LOCK_PINS {I0:A6} [get_cells ro0/not12/b_INST_0]
#set_property BEL A6LUT [get_cells ro0/not22/b_INST_0]
#set_property LOC SLICE_X36Y93 [get_cells ro0/not22/b_INST_0]
#set_property LOCK_PINS {I0:A6} [get_cells ro0/not22/b_INST_0]
#set_property BEL F7AMUX [get_cells ro0/dedimux2]
#set_property LOC SLICE_X36Y93 [get_cells ro0/dedimux2]
#set_property BEL B6LUT [get_cells ro0/not13/b_INST_0]
#set_property LOC SLICE_X37Y93 [get_cells ro0/not13/b_INST_0]
#set_property LOCK_PINS {I0:A1} [get_cells ro0/not13/b_INST_0]
#set_property BEL A6LUT [get_cells ro0/not23/b_INST_0]
#set_property LOC SLICE_X37Y93 [get_cells ro0/not23/b_INST_0]
#set_property LOCK_PINS {I0:A1} [get_cells ro0/not23/b_INST_0]
#set_property BEL F7AMUX [get_cells ro0/dedimux3]
#set_property LOC SLICE_X37Y93 [get_cells ro0/dedimux3]

#set_property BEL B6LUT [get_cells ro0/not14/b_INST_0]
#set_property LOC SLICE_X36Y94 [get_cells ro0/not14/b_INST_0]
#set_property LOCK_PINS {I0:A1} [get_cells ro0/not14/b_INST_0]
#set_property BEL A6LUT [get_cells ro0/not24/b_INST_0]
#set_property LOC SLICE_X36Y94 [get_cells ro0/not24/b_INST_0]
#set_property LOCK_PINS {I0:A1} [get_cells ro0/not24/b_INST_0]
#set_property BEL F7AMUX [get_cells ro0/dedimux4]
#set_property LOC SLICE_X36Y94 [get_cells ro0/dedimux4]
#set_property BEL B6LUT [get_cells ro0/not15/b_INST_0]
#set_property LOC SLICE_X37Y94 [get_cells ro0/not15/b_INST_0]
#set_property LOCK_PINS {I0:A1} [get_cells ro0/not15/b_INST_0]
#set_property BEL A6LUT [get_cells ro0/not25/b_INST_0]
#set_property LOC SLICE_X37Y94 [get_cells ro0/not25/b_INST_0]
#set_property LOCK_PINS {I0:A1} [get_cells ro0/not25/b_INST_0]
#set_property BEL F7AMUX [get_cells ro0/dedimux5]
#set_property LOC SLICE_X37Y94 [get_cells ro0/dedimux5]
##set_property BEL B6LUT [get_cells ro0/not16/b_INST_0]
##set_property LOC SLICE_X36Y95 [get_cells ro0/not16/b_INST_0]
##set_property LOCK_PINS {I0:A1} [get_cells ro0/not16/b_INST_0]
##set_property BEL A6LUT [get_cells ro0/not26/b_INST_0]
##set_property LOC SLICE_X36Y95 [get_cells ro0/not26/b_INST_0]
##set_property LOCK_PINS {I0:A1} [get_cells ro0/not26/b_INST_0]
##set_property BEL F7AMUX [get_cells ro0/dedimux6]
##set_property LOC SLICE_X36Y95 [get_cells ro0/dedimux6]
##set_property BEL B6LUT [get_cells ro0/not17/b_INST_0]
##set_property LOC SLICE_X37Y95 [get_cells ro0/not17/b_INST_0]
##set_property LOCK_PINS {I0:A1} [get_cells ro0/not17/b_INST_0]
##set_property BEL A6LUT [get_cells ro0/not27/b_INST_0]
##set_property LOC SLICE_X37Y95 [get_cells ro0/not27/b_INST_0]
##set_property LOCK_PINS {I0:A1} [get_cells ro0/not27/b_INST_0]
##set_property BEL F7AMUX [get_cells ro0/dedimux7]
##set_property LOC SLICE_X37Y95 [get_cells ro0/dedimux7]
## User Generated miscellaneous constraints

#set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {ro0/tem[0]}]

#set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets encro/qnro]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets encro/b]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets encro/c]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets encro/d]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets encro/e]

#create_clock -period 10.000 -name extclk -waveform {0.000 5.000} -add [get_ports clk]
#create_generated_clock -name uartclk -source [get_ports clk] -divide_by 1 [get_nets uartclk]
