webtalk_init -webtalk_dir /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.sim/sim_1/behav/xsim/xsim.dir/tb_enhancedCROwrap_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov  8 09:48:21 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211055993_1777508765_210667687_822" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ded81788-98cc-4e60-9c2e-f9d24c1359e6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "19071c6f73504fc5b9b68755951cfe2c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3691.017 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2550 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "36.56_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7334272_KB" -context "xsim\\usage"
webtalk_transmit -clientid 237710473 -regid "211055993_1777508765_210667687_822" -xml /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.sim/sim_1/behav/xsim/xsim.dir/tb_enhancedCROwrap_behav/webtalk/usage_statistics_ext_xsim.xml -html /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.sim/sim_1/behav/xsim/xsim.dir/tb_enhancedCROwrap_behav/webtalk/usage_statistics_ext_xsim.html -wdm /opt/Xilinx/Vivado/2018.1/bin/EnhancedCRO/EnhancedCRO.sim/sim_1/behav/xsim/xsim.dir/tb_enhancedCROwrap_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
